# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hear.proto import cleaner_v2_pb2 as hear_dot_proto_dot_cleaner__v2__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hear/proto/cleaner_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CleanerExecutionStub(object):
    """Internal proposed v2 boundary. Not registered by the legacy Pipeline server.
    Authentication, current-fence authorization and bounded semantic validation
    are mandatory; protobuf parsing is not admission. Never expose grants publicly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAttempt = channel.unary_unary(
                '/hear.cleaner.v2.CleanerExecution/ExecuteAttempt',
                request_serializer=hear_dot_proto_dot_cleaner__v2__pb2.ExecuteAttemptRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_cleaner__v2__pb2.ManifestReference.FromString,
                _registered_method=True)


class CleanerExecutionServicer(object):
    """Internal proposed v2 boundary. Not registered by the legacy Pipeline server.
    Authentication, current-fence authorization and bounded semantic validation
    are mandatory; protobuf parsing is not admission. Never expose grants publicly.
    """

    def ExecuteAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CleanerExecutionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAttempt,
                    request_deserializer=hear_dot_proto_dot_cleaner__v2__pb2.ExecuteAttemptRequest.FromString,
                    response_serializer=hear_dot_proto_dot_cleaner__v2__pb2.ManifestReference.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hear.cleaner.v2.CleanerExecution', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hear.cleaner.v2.CleanerExecution', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CleanerExecution(object):
    """Internal proposed v2 boundary. Not registered by the legacy Pipeline server.
    Authentication, current-fence authorization and bounded semantic validation
    are mandatory; protobuf parsing is not admission. Never expose grants publicly.
    """

    @staticmethod
    def ExecuteAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.cleaner.v2.CleanerExecution/ExecuteAttempt',
            hear_dot_proto_dot_cleaner__v2__pb2.ExecuteAttemptRequest.SerializeToString,
            hear_dot_proto_dot_cleaner__v2__pb2.ManifestReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
