# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from hear.proto import pipeline_pb2 as hear_dot_proto_dot_pipeline__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hear/proto/pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PipelineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/SubmitJob',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/hear.pipeline.v1.Pipeline/Subscribe',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.PipelineEvent.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/GetResult',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.GetResultRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.JobResult.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/CancelJob',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.GetResultRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.JobResult.FromString,
                _registered_method=True)
        self.GetQueueStats = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/GetQueueStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.QueueStatsReply.FromString,
                _registered_method=True)
        self.Moderate = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/Moderate',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.TextRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.ModerationReply.FromString,
                _registered_method=True)
        self.Categorize = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/Categorize',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.CategorizeRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.CategorizationReply.FromString,
                _registered_method=True)
        self.CreatePreview = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/CreatePreview',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.ReconstructRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.CreatePreviewReply.FromString,
                _registered_method=True)
        self.ConfirmPreview = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/ConfirmPreview',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.ConfirmPreviewReply.FromString,
                _registered_method=True)
        self.RemoveSegment = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/RemoveSegment',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.RemoveSegmentRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.RemoveSegmentReply.FromString,
                _registered_method=True)
        self.RollbackPreview = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/RollbackPreview',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.RollbackPreviewReply.FromString,
                _registered_method=True)
        self.GetPreview = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/GetPreview',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.Preview.FromString,
                _registered_method=True)
        self.ListDiscovery = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/ListDiscovery',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.ListDiscoveryReply.FromString,
                _registered_method=True)
        self.TrainCategorizer = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/TrainCategorizer',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.TrainRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.TrainReply.FromString,
                _registered_method=True)
        self.IngestCategoryEvent = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/IngestCategoryEvent',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.CategoryEvent.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.IngestReply.FromString,
                _registered_method=True)
        self.UpdatePlatformSettings = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/UpdatePlatformSettings',
                request_serializer=hear_dot_proto_dot_pipeline__pb2.PlatformSettingsRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.PlatformSettingsReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/hear.pipeline.v1.Pipeline/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hear_dot_proto_dot_pipeline__pb2.HealthReply.FromString,
                _registered_method=True)


class PipelineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moderate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Categorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmPreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSegment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackPreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDiscovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainCategorizer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestCategoryEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlatformSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.SubmitJobRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.SubmitJobResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.SubscribeRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.PipelineEvent.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.GetResultRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.JobResult.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.GetResultRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.JobResult.SerializeToString,
            ),
            'GetQueueStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.QueueStatsReply.SerializeToString,
            ),
            'Moderate': grpc.unary_unary_rpc_method_handler(
                    servicer.Moderate,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.TextRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.ModerationReply.SerializeToString,
            ),
            'Categorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Categorize,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.CategorizeRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.CategorizationReply.SerializeToString,
            ),
            'CreatePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePreview,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.ReconstructRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.CreatePreviewReply.SerializeToString,
            ),
            'ConfirmPreview': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmPreview,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.ConfirmPreviewReply.SerializeToString,
            ),
            'RemoveSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSegment,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.RemoveSegmentRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.RemoveSegmentReply.SerializeToString,
            ),
            'RollbackPreview': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackPreview,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.RollbackPreviewReply.SerializeToString,
            ),
            'GetPreview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreview,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.PreviewRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.Preview.SerializeToString,
            ),
            'ListDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDiscovery,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.DiscoveryRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.ListDiscoveryReply.SerializeToString,
            ),
            'TrainCategorizer': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainCategorizer,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.TrainRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.TrainReply.SerializeToString,
            ),
            'IngestCategoryEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestCategoryEvent,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.CategoryEvent.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.IngestReply.SerializeToString,
            ),
            'UpdatePlatformSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlatformSettings,
                    request_deserializer=hear_dot_proto_dot_pipeline__pb2.PlatformSettingsRequest.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.PlatformSettingsReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hear_dot_proto_dot_pipeline__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hear.pipeline.v1.Pipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hear.pipeline.v1.Pipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pipeline(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/SubmitJob',
            hear_dot_proto_dot_pipeline__pb2.SubmitJobRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/Subscribe',
            hear_dot_proto_dot_pipeline__pb2.SubscribeRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.PipelineEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/GetResult',
            hear_dot_proto_dot_pipeline__pb2.GetResultRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.JobResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/CancelJob',
            hear_dot_proto_dot_pipeline__pb2.GetResultRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.JobResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/GetQueueStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.QueueStatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Moderate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/Moderate',
            hear_dot_proto_dot_pipeline__pb2.TextRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.ModerationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Categorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/Categorize',
            hear_dot_proto_dot_pipeline__pb2.CategorizeRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.CategorizationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/CreatePreview',
            hear_dot_proto_dot_pipeline__pb2.ReconstructRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.CreatePreviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/ConfirmPreview',
            hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.ConfirmPreviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/RemoveSegment',
            hear_dot_proto_dot_pipeline__pb2.RemoveSegmentRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.RemoveSegmentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/RollbackPreview',
            hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.RollbackPreviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/GetPreview',
            hear_dot_proto_dot_pipeline__pb2.PreviewRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.Preview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/ListDiscovery',
            hear_dot_proto_dot_pipeline__pb2.DiscoveryRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.ListDiscoveryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainCategorizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/TrainCategorizer',
            hear_dot_proto_dot_pipeline__pb2.TrainRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.TrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestCategoryEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/IngestCategoryEvent',
            hear_dot_proto_dot_pipeline__pb2.CategoryEvent.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.IngestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlatformSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/UpdatePlatformSettings',
            hear_dot_proto_dot_pipeline__pb2.PlatformSettingsRequest.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.PlatformSettingsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.pipeline.v1.Pipeline/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hear_dot_proto_dot_pipeline__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
