# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hear.proto import resolver_pb2 as hear_dot_proto_dot_resolver__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hear/proto/resolver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResolverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/hear.resolver.v1.Resolver/Resolve',
                request_serializer=hear_dot_proto_dot_resolver__pb2.ResolveRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_resolver__pb2.ResolveReply.FromString,
                _registered_method=True)
        self.ResolverHealth = channel.unary_unary(
                '/hear.resolver.v1.Resolver/ResolverHealth',
                request_serializer=hear_dot_proto_dot_resolver__pb2.HealthRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_resolver__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Rebuild = channel.unary_unary(
                '/hear.resolver.v1.Resolver/Rebuild',
                request_serializer=hear_dot_proto_dot_resolver__pb2.RebuildRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_resolver__pb2.RebuildReply.FromString,
                _registered_method=True)
        self.Apply = channel.unary_unary(
                '/hear.resolver.v1.Resolver/Apply',
                request_serializer=hear_dot_proto_dot_resolver__pb2.RebuildRequest.SerializeToString,
                response_deserializer=hear_dot_proto_dot_resolver__pb2.RebuildReply.FromString,
                _registered_method=True)


class ResolverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolverHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rebuild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=hear_dot_proto_dot_resolver__pb2.ResolveRequest.FromString,
                    response_serializer=hear_dot_proto_dot_resolver__pb2.ResolveReply.SerializeToString,
            ),
            'ResolverHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolverHealth,
                    request_deserializer=hear_dot_proto_dot_resolver__pb2.HealthRequest.FromString,
                    response_serializer=hear_dot_proto_dot_resolver__pb2.HealthReply.SerializeToString,
            ),
            'Rebuild': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebuild,
                    request_deserializer=hear_dot_proto_dot_resolver__pb2.RebuildRequest.FromString,
                    response_serializer=hear_dot_proto_dot_resolver__pb2.RebuildReply.SerializeToString,
            ),
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=hear_dot_proto_dot_resolver__pb2.RebuildRequest.FromString,
                    response_serializer=hear_dot_proto_dot_resolver__pb2.RebuildReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hear.resolver.v1.Resolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hear.resolver.v1.Resolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Resolver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.resolver.v1.Resolver/Resolve',
            hear_dot_proto_dot_resolver__pb2.ResolveRequest.SerializeToString,
            hear_dot_proto_dot_resolver__pb2.ResolveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolverHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.resolver.v1.Resolver/ResolverHealth',
            hear_dot_proto_dot_resolver__pb2.HealthRequest.SerializeToString,
            hear_dot_proto_dot_resolver__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rebuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.resolver.v1.Resolver/Rebuild',
            hear_dot_proto_dot_resolver__pb2.RebuildRequest.SerializeToString,
            hear_dot_proto_dot_resolver__pb2.RebuildReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hear.resolver.v1.Resolver/Apply',
            hear_dot_proto_dot_resolver__pb2.RebuildRequest.SerializeToString,
            hear_dot_proto_dot_resolver__pb2.RebuildReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
